name: "Bulid and upload"
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-linux
          - target: x86_64-linux
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install -y qemu-user-static
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
            system = ${{ matrix.target }}
    - run: nix build '.#packages.${{ matrix.target }}.wlrune-static'
    - run: nix flake check
    - run: cp -vL ./result/bin/wlrune wlrune-${{ matrix.target }}
    - uses: actions/upload-artifact@v4
      with:
        name: wlrune-${{ matrix.target }}
        path: ./wlrune-${{ matrix.target }}
        if-no-files-found: "error"
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: "artifacts/"
      - run: ls -la artifacts/*
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            artifacts/**/wlrune-*

